---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 4
  network:
    - ["forwarded_port", {guest: 80, host: 80}]
    - ["private_network", {ip: "192.168.35.10"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: '14.12.9'

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[tsd-chef::default]
    attributes:
